# Generated by Django 3.2.22 on 2023-10-26 08:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField()),
                ('fecha_de_asignacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('duracion_estimada', models.FloatField()),
                ('fecha_de_inicio', models.DateField()),
                ('fecha_de_finalizacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo_electronico', models.CharField(max_length=50, unique=True)),
                ('contraseña', models.CharField(max_length=20)),
                ('fecha_de_registro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('prioridad', models.IntegerField()),
                ('estados', models.CharField(choices=[('PEN', 'Pendiente'), ('PRO', 'Progreso'), ('COM', 'Completada')], default='PEN', max_length=3)),
                ('completada', models.BooleanField(default=False)),
                ('fecha_de_creacion', models.DateField()),
                ('hora_de_vencimiento', models.TimeField()),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_modelos.proyecto')),
                ('usuario_creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_modelos.usuario')),
                ('usuarios_asignados', models.ManyToManyField(related_name='usuarios_asignados', through='a_modelos.AsignacionTarea', to='a_modelos.Usuario')),
            ],
        ),
        migrations.AddField(
            model_name='proyecto',
            name='usuario',
            field=models.ManyToManyField(related_name='usuario', to='a_modelos.Usuario'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='usuario_creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_creador', to='a_modelos.usuario'),
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('tarea', models.ManyToManyField(to='a_modelos.Tarea')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha_de_contenido', models.DateTimeField(default=django.utils.timezone.now)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_modelos.tarea')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_modelos.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='asignaciontarea',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_modelos.tarea'),
        ),
        migrations.AddField(
            model_name='asignaciontarea',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_modelos.usuario'),
        ),
    ]
