# Generated by Django 3.2.12 on 2023-10-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_modelos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='usuario',
            field=models.ManyToManyField(to='a_modelos.Usuario'),
        ),
    ]
